### PR TITLE
Use Github Actions

### LINKED ISSUE #63: publish new release (and support packer init)
Now that #62 is merged and the plugin works again with the newest version of packer a new release should be published.
Ideally the release process should be updated, so that the plugin supports `packer init` as documented [here](https://github.com/lmars/packer-post-processor-vagrant-s3/pull/62#issuecomment-825221567).
Friendly ping @lmars @Jalle19.

### LINKED ISSUE #64: Replace Travis CI with GitHub Actions or something
Can't make a new release right now because Travis CI is gone

### PR DESCRIPTION
**Pull request by floh96**
Closes #64
Closes #63

This pr switches the ci to github actions.
It uses the github workflow provided by hashicorp.
I have created a release on my fork using this code https://github.com/floh96/packer-plugin-vagrant-s3/releases
This pr needs some prerequisites before merging:

* the repository musst be renamed to `packer-plugin-vagrant-s3`
* a gpg key for signing the releases musst be added
* therefor 2 repository secrets musst be created 
* GPG_PRIVATE_KEY and PASSPHRASE

After merging a new release can be published by pushing the following tag `v1.6.0`

### CODE REVIEW

**Comment by Jalle19** [comment]
Looks good!

**Comment by rsutton1** [comment]
Any updates here?

**Comment by floh96** [comment]
@rsutton1 see https://github.com/lmars/packer-post-processor-vagrant-s3/issues/64#issuecomment-964121012 the ci setup is working, unfortunately the post-processor was not  working for me and I wasn't able to figure out what the problem is.
I won't be able to spend time finishing this also the chance that it gets merged upstream is low, the repo seems to be dead.
You could try using https://github.com/floh96/packer-plugin-vagrant-s3/releases/tag/v1.5.2 maybe you can figure out what the problem is.

**Comment by rsutton1** [comment]
@floh96 Thanks for the quick response. When I put this in my Packer file and run `packer init .` it works as expected:

```
packer {
  required_plugins {
    vagrant-s3 = {
      version = ">= 1.5.2"
      source  = "github.com/floh96/vagrant-s3"
    }
  }
}
```

Thanks!

**Comment by floh96** [comment]
@rsutton1 thanks for validating that it is working don't know what was the problem for me two years ago...
I have created a pr upstream maybe it will get merged and will close this pr.

**Pull request closed without merging**
